apiVersion: apps/v1
kind: Deployment
metadata:
    name: greeting-blob-storage
spec:
    selector:
        matchLabels:
            app: greeting-blob-storage
    template:
        metadata:
            labels:
                app: greeting-blob-storage
        spec:
            containers:
                -   name: greeting-blob-storage
                    image: mcr.microsoft.com/azure-storage/azurite:latest
                    ports:
                        -   containerPort: 10000

#                    env:
#                        -   name: POSTGRES_DB
#                            valueFrom:
#                                configMapKeyRef:
#                                    key: POSTGRES_DB
#                                    name: greeting-blob-storage-config
#                        -   name: POSTGRES_USER
#                            valueFrom:
#                                configMapKeyRef:
#                                    key: POSTGRES_USER
#                                    name: greeting-blob-storage-config
#                        -   name: POSTGRES_PASSWORD
#                            valueFrom:
#                                secretKeyRef:
#                                    key: POSTGRES_PASSWORD
#                                    name: greeting-blob-storage-secret
                    command:
                        - "azurite-blob"
#                        - "--blobHost 0.0.0.0 "
#                        - "--blobPort 10000"
---
apiVersion: v1
kind: Service
metadata:
    name: greeting-blob-storage-service
spec:
    ports:
        - port: 10000
          targetPort: 10000
    selector:
        app: greeting-blob-storage
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#    name: greeting-blob-storage-config
#    labels:
#        app: greeting-blob-storage
#data:
#    POSTGRES_DB: "greeting_rust"
#    POSTGRES_USER: "greeting_rust"
#    POSTGRES_HOST: "greeting_rust"
#---
#apiVersion: v1
#kind: Secret
#metadata:
#    name: greeting-blob-storage-secret
#    labels:
#        app: greeting-blob-storage
#data:
#    POSTGRES_PASSWORD: Z3JlZXRpbmdfcnVzdAo=